### ISSUE TITLE
USVFS Issues on Windows 11 24H2

### ISSUE THREAD

**Issue by wxMichael** [ModOrganizer2/modorganizer#2174]
## The problem:
On Windows 11 24H2, checks for files existing in Python apps launched via MO2 fail for any file that is in the VFS but _not_ overriding a file actually present in Data/.
None of the following work:
- os.path: `exists()` / `isfile()` / `isdir()`
- pathlib.Path: `exists()` / `is_file()` / `is_dir()` / `glob()`

e.g. `path.is_dir()` will return False while `path.iterdir()` returns its contents. 

## To Reproduce:

1. Create a bat file to launch repro.py: `python repro.py`
2. Create a file `repro.py` with the below code.
3. Change the file path to a file that is present in the VFS but not present in the actual Data folder.
4. Launch the bat via MO2.
```python
import sys
from pathlib import Path

if sys.getwindowsversion().build != 26100:
	print("This repro requires Windows 11 24H2")
else:
	# Provide a file or folder present only in the VFS
	file = Path(R"C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE\Plugins\Buffout4.dll")
	print(f"""path: {file}
exists: {file.exists()}
is_file: {file.is_file()}
is_dir: {file.is_dir()}
iterdir: {next(f for f in file.parent.iterdir() if f.name == file.name)}""")
input()
```

## Environment:

* Mod Organizer Version that exhibits the issue: 2.5.2
* Last Mod Organizer Version that did not exhibit the issue (if applicable): N/A
* Desktop OS/version used to run Mod Organizer: Windows 11 Home 24H2 26100.2605

## Details:

Output showing the file existing but checks failing:
```
path: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE\Plugins\Buffout4.dll
exists: False
is_file: False
is_dir: False
iterdir: C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\Data\F4SE\Plugins\Buffout4.dll
```

**Comment by HarrierCZ** [comment]
Can someone check if my issue posted [here](https://github.com/ModOrganizer2/modorganizer/issues/1808#issuecomment-2551277430) is relevant to this isue? I also have Windows 11 24H2.

**Comment by HarrierCZ** [comment]
Can someone check if my issue posted [here](https://github.com/ModOrganizer2/modorganizer/issues/1808#issuecomment-2551277430) is relevant to this isue? I also have Windows 11 24H2.

**Comment by wxMichael** [comment]
Related issue/commits from Wrye Bash:  
- https://github.com/wrye-bash/wrye-bash/issues/689 
- https://github.com/wrye-bash/wrye-bash/commit/d3f11abfcbf7e547dfe57f173bc22a46dcd849ef 
- https://github.com/wrye-bash/wrye-bash/commit/a8339b895b4e4443dcee03882a9aae742bf289c0

**Comment by Cutleast** [comment]
This may be related to the starting issues of Python executables built with cx_Freeze or PyInstaller, that I encountered, recently:
- https://github.com/Cutleast/Dynamic-Interface-Patcher/issues/7
- https://github.com/Cutleast/Dynamic-Interface-Patcher/issues/5

The AV part was fixed in the meantime, but the issues with launching via MO2 persist.

**Comment by Holt59** [comment]
The above code works fine with 24H2 and Python 3.11. Are you sure this is related to Windows 24H2 and not Python 3.12?

**Comment by Holt59** [comment]
Unless someone reproduces the issue with Python 3.11 on Windows 24H2, I would say the issue comes from the use of [`GetFileInformationByName`](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getfileinformationbyname) in the `os.stat` implementation starting from Python 3.12.

Hooking `GetFileInformationByName` seems to fix the issue although I am not sure if this is would be the lowest-level function to hook for this.

**Comment by Holt59** [comment]
> Wine doesn't seem to have an implementation of `GetFileInformationByName` (based on a search of their GitHub mirror), so we can't base our hook on where they decide to stop pretending to be Windows and start calling Unix functions.

I went down to `NtQueryInformationByName` which seems to also fix the issue (without hooking `GetFileInformationByName`).

As far as I can tell, Wine does that even deeper by hooking `ObXXX` calls, like `ObOpenObjectByName` or `ObQueryNameString`. Since we have never dealt with this kind of API Calls, I don't want to go down that rabbit hole for now.

**Comment by Holt59** [comment]
@wxMichael @Cutleast You can try this version of USVFS if you want - I am not 100% sure I did not modify the API between MO2 and USVFS, so these may not work at all but let me know if you try them.

[usvfs_0.5.7.0.zip](https://github.com/user-attachments/files/18222563/usvfs_0.5.7.0.zip)

**Comment by Cutleast** [comment]
Can confirm that it fixes the issues with the Pyinstaller build of DIP, didn't test it with cx_Freeze, though.

And since DIP makes use of `pathlib.Path.is_file()` and `pathlib.Path.is_dir()`, those seem to be fine, too.

**Comment by wxMichael** [comment]
> The above code works fine with 24H2 and Python 3.11. Are you sure this is related to Windows 24H2 and not Python 3.12?

It's possible it's also specific to Python 3.12+.
My project has been using 3.12 for a while without issue until I updated to 24H2 to test my suspicion that it's what was causing my users trouble.

**Comment by Cutleast** [comment]
Update: While fixing the issues with the cx_Freeze build, it broke the Nuitka build. It just throws this error message:
![Image](https://github.com/user-attachments/assets/d960f54e-e37e-46d6-9058-ffe9fa7a28db)
and then crashes immediately.

**Comment by wxMichael** [comment]
@Holt59 That version of USVFS does work with the repro code on my PC, both when run from source and when compiled with PyInstaller.

**Comment by Holt59** [comment]
> Update: While fixing the issues with the cx_Freeze build, it broke the Nuitka build. It just throws this error message: ![Image](https://github.com/user-attachments/assets/d960f54e-e37e-46d6-9058-ffe9fa7a28db) and then crashes immediately.

Can you provide a reproducible example? I tried building DIP but it fails to run even outside of MO2 so I cannot really check anything.

**Comment by Cutleast** [comment]
Here you go, a minimal reproducable example (I just adapted OP's repro to test an import from PySide6). The command to build the executable is in the first line.

```python
# nuitka --msvc="latest" --standalone --windows-console-mode=force --enable-plugin=pyside6 --remove-output --nofollow-import-to=tkinter "usvfs_test.py"

import sys
from pathlib import Path

from PySide6.QtWidgets import QApplication

if sys.getwindowsversion().build != 26100:
    print("This repro requires Windows 11 24H2")
else:
    # Provide a file or folder present only in the VFS
    file = Path(R".\DIP\DIP.exe")
    print(f"""path: {file}
exists: {file.exists()}
is_file: {file.is_file()}
is_dir: {file.is_dir()}
iterdir: {next(f for f in file.parent.iterdir() if f.name == file.name)}""")
input()
```

When launched via MO2, the same error and crash occur:
```
PySide6/__init__.py: Unable to import Shiboken from C:\Games\Skyrim Special Edition\data\usvfs_test.dist, C:\Games\SKYRIM~1\data\usvfs_test.dist
Traceback (most recent call last):
  File "C:\Games\SKYRIM~1\data\usvfs_test.dist\usvfs_test.py", line 6, in <module>
  File "C:\Games\SKYRIM~1\data\usvfs_test.dist\PySide6\__init__.py", line 123, in <module PySide6>
  File "C:\Games\SKYRIM~1\data\usvfs_test.dist\PySide6\__init__.py", line 62, in _setupQtDirectories
  File "C:\Games\SKYRIM~1\data\usvfs_test.dist\shiboken6\__init__.py", line 27, in <module shiboken6>
ImportError: LoadLibraryExW 'C:\Games\SKYRIM~1\data\usvfs_test.dist\shiboken6\Shiboken.pyd' failed: The specified module could not be found.
```

**Comment by Holt59** [comment]
> Here you go, a minimal reproducable example (I just adapted OP's repro to test an import from PySide6). The command to build the executable is in the first line.
> 

I cannot reproduce... I get 

```
[WinError 3] The system cannot find the path specified: 'DIP'
```

...which is 100% expected since I do not have such folder, but that also means that the `PySide6` import went well.

Does `C:\Games\SKYRIM~1\data\usvfs_test.dist\shiboken6\Shiboken.pyd` actually exists on your side? Does it work outside of MO2?

**Comment by Cutleast** [comment]
It works outside of MO2 and Explorer++ says, it exists within the VFS:
![Image](https://github.com/user-attachments/assets/ad40d6b6-5963-49f5-865d-58b578757ef4)

**Comment by Holt59** [comment]
> **Here's some more information about the environment:** Python: 3.12.4 Nuitka: 2.5.6 PySide6: 6.8.0.2 shiboken6: 6.8.0.2 MO2: 2.5.2 UVFS: the files you provided, some hours ago Windows: 26100.2605
> 
> UVFS Log: https://gist.github.com/Cutleast/451bb5d0e9119bb621bdf0c4904d167e MO2 Interface Log: https://gist.github.com/Cutleast/eed0b4895174a007d08c3e303d85a156

Okay I was simply launching the executable through MO2 but if I understand correctly you are actually launching a bat file that launches the executable that is in the VFS?

**Comment by Cutleast** [comment]
I just created it to better capture the error message since it immediately closes:
```batch
usvfs_test.exe
pause
```

**Comment by Holt59** [comment]
> I just created it to better capture the error message since it immediately closes:
> 
> usvfs_test.exe
> pause
> 
> Starting the exe directly doesn't change the outcome.

I cannot reproduce, with or without `.bat`, I tried with relative/absolute paths everywhere, etc., but to no avail...

Can you try with a MO2 instance with only a mod containing the build executable (+ dependencies) and launch it once (with debug logs) to get clean USVFS logs?

**Comment by Cutleast** [comment]
I now created a new portable instance, fresh from MO2 v2.5.2 (+ your UVFS files) and set the log level to "Debug":
USVFS Log: https://gist.github.com/Cutleast/6ba546e15586872c108d35eeab984d2e
MO2 Interface Log: https://gist.github.com/Cutleast/e4340f85db8fbe2baf7bcc37052b30db

**Comment by Infernio** [comment]
> [@wxMichael](https://github.com/wxMichael) [@Cutleast](https://github.com/Cutleast) You can try this version of USVFS if you want - I am not 100% sure I did not modify the API between MO2 and USVFS, so these may not work at all but let me know if you try them.
> 
> [usvfs_0.5.7.0.zip](https://github.com/user-attachments/files/18222563/usvfs_0.5.7.0.zip)

What's the status here? We get complaints in the WB Discord about this issue daily. Can this fix be landed in a new MO2 release?

**Comment by Cutleast** [comment]
I'm currently testing a workaround in DIP on our Discord server because we're getting similar reports and I pushed the workaround to a separate branch. Take a look if you're interested (compare with master to filter for the issue-related changes):
https://github.com/Cutleast/Dynamic-Interface-Patcher/tree/8-mo2-uvfs-issues-on-windows-11-24h2

**Comment by wxMichael** [comment]
This issue may not be limited to just Python. I have a C# app made with the Hello World console app template that crashes instantly on launch but only on Windows 11 24H2 via MO2.
If TargetFramework is set to net9.0 and RuntimeIdentifier is set to win-x64 MO2 can't run it.
The USVFS test files shared above don't resolve the issue.
`ConsoleApp1.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <ImplicitUsings>enable</ImplicitUsings>
        <PublishSelfContained>True</PublishSelfContained>
        <PublishSingleFile>True</PublishSingleFile>
        <PublishTrimmed>True</PublishTrimmed>
    </PropertyGroup>
</Project>
```
`Program.cs`:
```csharp
internal class Program
{
    private static void Main(string[] args)
    {
        Console.WriteLine("Hello, World!");
        Console.ReadLine();
    }
}
```
I've attached the C# solution along with a compiled exe and the logs from USVFS and Process Monitor attempting to launch it.
The exe was built running just `dotnet publish`
[usvfs-2025-01-25_19-29-44.log](https://github.com/user-attachments/files/18548326/usvfs-2025-01-25_19-29-44.log)
[ProcMonLog.zip](https://github.com/user-attachments/files/18548333/ProcMonLog.zip)
[ConsoleApp1.zip](https://github.com/user-attachments/files/18548334/ConsoleApp1.zip)

**Comment by Silarn** [comment]
@Holt59 Am I understanding correctly that the original issue is due to running an externally compiled python app through USVFS? As in not a MO2 python plugin, but a packaged EXE.

I guess we should consider a minor release to patch that and perhaps a few other smaller issues here.

**Comment by wxMichael** [comment]
@Silarn My repro case in the first post is a bare py file run with a bat file using the system's installed Python.
The issue also occurs when running an exe compiled with PyInstaller.
Compiled exes like that also crash immediately if installed as a mod and run from within the VFS.

**Comment by Silarn** [comment]
Right. At the end of the day, it requires an external copy of python, which corroborates Holt's assumption and hopefully the USVFS fix will resolve it. I'll see if I can pull that and test myself in a while. Does this apply to the latest WB releases?

**Comment by Liderate** [comment]
Yes, the issue happens with Wrye Bash 313 from Nexus Mods.

**Comment by esbe1175** [comment]
Just wanted to add that I am having problems with this as well. Some applications run just fine, while others break or won' run at all. Worked fine before i updated.

**Comment by transbiod** [comment]
Can confirm that Wrye Bash 313 has the same problem

**Comment by Aqvilinus** [comment]
@Silarn do you have an estimate for when this will be fixed, or can you provide a temporary solution in the meantime?

**Comment by Holt59** [comment]
> [@Silarn](https://github.com/Silarn) do you have an estimate for when this will be fixed, or can you provide a temporary solution in the meantime?

Did you test https://github.com/ModOrganizer2/modorganizer/issues/2174#issuecomment-2558511974? If that does not work, then the fix will probably take a long time...

**Comment by transbiod** [comment]
> > [@Silarn](https://github.com/Silarn) do you have an estimate for when this will be fixed, or can you provide a temporary solution in the meantime?
> 
> Did you test [#2174 (comment)](https://github.com/ModOrganizer2/modorganizer/issues/2174#issuecomment-2558511974)? If that does not work, then the fix will probably take a long time...

It worked for me, no problems launching Wrye Bash with this files installed

**Comment by Silarn** [comment]
@Liderate How do I confirm the issue? Even before trying to build Holt's changes above I ran a local Wrye just with the 'GetModuleFileNameA' hook added back in an attempt to resolve #2217 and didn't immediately notice a problem.

**Comment by Silarn** [comment]
With Holt's code it does seem to be working:

![Image](https://github.com/user-attachments/assets/919540fc-9eb1-4bb4-bdd1-f55967c8153d)

Without it:

![Image](https://github.com/user-attachments/assets/aad7381a-2faf-4ecc-9eb2-37003f708a00)

**Comment by Liderate** [comment]
> [@Liderate](https://github.com/Liderate) How do I confirm the issue? Even before trying to build Holt's changes above I ran a local Wrye just with the 'GetModuleFileNameA' hook added back in an attempt to resolve [#2217](https://github.com/ModOrganizer2/modorganizer/issues/2217) and didn't immediately notice a problem.

I used the Wrye Bash v313 Standalone Executable and MO2 2.5.2 release. I launched `Wrye Bash.exe` through MO2, selected a game, clicked Launch, then was met with an error box.

**Comment by Silarn** [comment]
Either launching an embedded version which auto-launches for the current game directory or a standalone version where I have to select the game is working for me with Holt's change, so far as I can tell. I even ran the game through the MO2-launched Wrye.

**Comment by Utumno** [comment]
Hi @Holt59 - what is the state of this?

**Comment by Wuerfelhusten** [comment]
[For all the python users](https://pypi.org/project/mo2-vfs.py/)

**Comment by Utumno** [comment]
> [For all the python users](https://pypi.org/project/mo2-vfs.py/)

Looks good (haven't tested it) but couldn't we have the patch by Holt @Silarn ? Having to monkey patch the std looks like a hell of maintenance issues.

**Comment by JonathanFeenstra** [comment]
We are working on a new release that includes the USVFS patch with the fix.
