### ISSUE TITLE
Oblivion attributerror:function 'cb_GetMajor' not found

### ISSUE THREAD

**Issue by bolzack** [ModOrganizer2/modorganizer#516]
Installed Wyrebash this morning.  Every time i try running it i get this same error.

Traceback (most recent call last):
  File "bash\bash.pyo", line 227, in main
  File "bash\bash.pyo", line 321, in _main
  File "zipextimporter.pyo", line 82, in load_module
  File "bash\bosh\__init__.pyo", line 45, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "bash\bosh\_mergeability.pyo", line 28, in <module>
  File "zipextimporter.pyo", line 82, in load_module
  File "bash\cint.pyo", line 214, in <module>
  File "ctypes\__init__.pyo", line 375, in __getattr__
  File "ctypes\__init__.pyo", line 380, in __getitem__
AttributeError: function 'cb_GetMajor' not found

**Comment by LostDragonist** [comment]
What version of MO2?  What version of Wrye Bash?  Python executable or standalone executable?  What game are we talking about here?  What version of Windows? Where are your logs as required by the issue template?

**Comment by bolzack** [comment]
Standalone executable. Wyre bash 370 beta 3.  Oblivion. Windows 10.  The error I posted is the only thing that pops up for me whenever i click on Wyre bash from the Mopy folder

**Comment by LostDragonist** [comment]
If you're launching WB from the folder directly, then you're not launching with it MO2.  Which means MO2 is not really involved.  You probably want to go ask the WB team instead.

I can tell you that the error you posted means you got an error while WB was trying to spit out information about another error.
